### PR TITLE
Chore/bump black to 22.10.0

### PR DESCRIPTION
**Pull request by hollandjg**
## Description

Update pre-commit hook "black" to newest.

### CODE REVIEW

**Comment by benwandrew** [comment]
is this handy at all?

https://chrisholdgraf.com/blog/2022/precommit-autoupdate/

**Comment by hollandjg** [comment]
> is this handy at all?
> 
> https://chrisholdgraf.com/blog/2022/precommit-autoupdate/

Hi Ben, I'm not sure. I think it would be super useful to have the dependabot support for this (which is mentioned in the article you linked) but it still requires a review each time we do the update, so perhaps the best way is just to regularly have a task within the group to update the pre-commit hooks one-by-one and fix any problems which occur in the code. For an instance where the automation didn't help us a lot, see #147

**Review by musslick — APPROVED** [review]
Happy to move to the new black!

**Comment by benwandrew** [comment]
> 

Gotcha, the recurring task makes sense to me then.

**Review by benwandrew — APPROVED** [review]
another clean update

**Pull request merged**
