### PR TITLE
503 fix broken links

### LINKED ISSUE #503: fix broken links
some links are broken (e.g in the tutorials)

### PR DESCRIPTION
**Pull request by younesStrittmatter**
# Description

- resolves #503

# Type of change

*Delete as appropriate:*
- **docs**: Documentation only changes

# Questions (Optional)
the links in the jupiter notebooks work, but it doesn't seem right. I brievly looked into the mkdocs-jupiter plugin documentation but didn't find much. I'll work on it when I find time, but this is a quick fix so at least it works.

### CODE REVIEW

**Review by benwandrew — COMMENTED** [review]
so the links as you changed them were not working for me, so i tested reverting one of the paths to the original and now it works. not sure why they weren't working for you before, or why they are working for me now...

**Comment by younesStrittmatter** [comment]
Weird... but they are not working on the website as they are now (../experimentalis/index.md) See here: https://autoresearch.github.io/autora/tutorials/

**Comment by younesStrittmatter** [comment]
Or are the website links working for you?

**Comment by younesStrittmatter** [comment]
online I mean. Not locally.

**Comment by benwandrew** [comment]
ah no, you're right. it's not working for me online as it originally was. happy to undo my commit and approve then as a temporary fix (at least to see what happens after merging this PR and rebuilding the site).

**Review by benwandrew — APPROVED** [review]

**Pull request merged**
