### PR TITLE
Feat/parallel pipe

### PR DESCRIPTION
**Pull request by hollandjg**
# Description

Add a ParallelPipeline object which passes the input to all the pipes independently and then concatenates the result.### 

# Type of change:
- New feature (non-breaking change which adds functionality)

# History

Suggested by @chadcwilliams and @younesStrittmatter:
> I [Younes] just chatted with Chad about the experimentalist, and he came up with a really great idea: As far as I understand, the experimentalist pipeline works like a bottleneck? So the output of a sampler gets fed into the following sampler, and so on. But it would be great to also "add" experimental conditions back in. For example, one could use the difference sampler, add conditions from the uncertainty sampler, and then randomly sample from the combined conditions. That way, instead of only being able to "sequentially" sample, we were able to sample "parallel". On a different note: Is it possible to use Pipelines in Pipelines? So one could build two different Sampler-Pipelines, parallelize them by "adding", and then build a Filter-Pipeline, that filters from them again. This would make the Pipeline very flexible. Maybe I am mistaken, and this is already possible, but if not, it might be worth thinking about implementing it.

### CODE REVIEW

**Review by gtdang — COMMENTED** [review]
I think this makes sense to me. I think it's a bit confusing to call it parallel since it can be confused with parallel processing. It's still sequential but the processes are independent of each other. Wondering if there is a better name for this?

**Comment by hollandjg** [comment]
> I think this makes sense to me. I think it's a bit confusing to call it parallel since it can be confused with parallel processing. It's still sequential but the processes are independent of each other. Wondering if there is a better name for this?

It's a good point. In principle, we could make them execute in parallel, if we put in the effort to make it happen. But you're right that they aren't doing that now.

How about `PipelineUnion` analog the scikit-learn `FeatureUnion` https://scikit-learn.org/stable/modules/compose.html#pipelines-and-composite-estimators

**Comment by gtdang** [comment]
> > I think this makes sense to me. I think it's a bit confusing to call it parallel since it can be confused with parallel processing. It's still sequential but the processes are independent of each other. Wondering if there is a better name for this?
> 
> It's a good point. In principle, we could make them execute in parallel, if we put in the effort to make it happen. But you're right that they aren't doing that now.
> 
> How about `PipelineUnion` analog the scikit-learn `FeatureUnion` https://scikit-learn.org/stable/modules/compose.html#pipelines-and-composite-estimators

Yeah that works!

**Comment by hollandjg** [comment]
Hi @gtdang – feel free to merge this whilst I'm away!

**Review by younesStrittmatter — APPROVED** [review]
Looks good to me.

**Review by gtdang — APPROVED** [review]
Approve!

**Pull request merged**
