### PR TITLE
added numpy compatibility for BMS predict method

### PR DESCRIPTION
**Pull request by musslick**
## Description

Added numpy functionality in predict method of BMS. This is necessary for BMS to work in the cycle with the popper experimentalist.

### Type of change:
- Bug fix (non-breaking change which fixes an issue)

### Features: 
- checks for numpy input and converts to pandas dataframe

### CODE REVIEW

**Review by benwandrew — COMMENTED** [review]
all tests passing and overall this looks good to me! i have just one question: does this change merit writing another test in which `predict` is initially passed a numpy array? or would that be redundant given the structure and purpose of our existing mcmc test? looks like that test exclusively uses a dataframe, so just curious for completeness purposes...

**Comment by benwandrew** [comment]
also, while tests are passing, workflow checks are not (again)...

**Comment by musslick** [comment]
> also, while tests are passing, workflow checks are not (again)...

Yeah, it seems so. Not sure how to address that... Perhaps ignore them for now since those are not related to the change? @hollandjg

**Comment by musslick** [comment]
> all tests passing and overall this looks good to me! i have just one question: does this change merit writing another test in which `predict` is initially passed a numpy array? or would that be redundant given the structure and purpose of our [existing mcmc test](https://github.com/AutoResearch/autora/blob/fix/bms-numpy-input/tests/test_bms_mcmc.py)? looks like that test exclusively uses a dataframe, so just curious for completeness purposes...

I don't think it's necessary since the change is quite straightforward. It would have made sense if there were more mcmc tests already but since it is just one, it might not be worth duplicating that with a numpy input instead of a df....

**Comment by benwandrew** [comment]
sounds

> > all tests passing and overall this looks good to me! i have just one question: does this change merit writing another test in which `predict` is initially passed a numpy array? or would that be redundant given the structure and purpose of our [existing mcmc test](https://github.com/AutoResearch/autora/blob/fix/bms-numpy-input/tests/test_bms_mcmc.py)? looks like that test exclusively uses a dataframe, so just curious for completeness purposes...
> 
> I don't think it's necessary since the change is quite straightforward. It would have made sense if there were more mcmc tests already but since it is just one, it might not be worth duplicating that with a numpy input instead of a df....

good deal, approved then!

**Review by benwandrew — APPROVED** [review]

**Review by TheLemonPig — APPROVED** [review]

**Pull request merged**
