### PR TITLE
Exploration: closed loop with darts random experimentalist

### PR DESCRIPTION
**Pull request by hollandjg**
## Description

Get the closed-loop cycle working with the DARTS theorist and a random experimenter. The example code is in the `tests/test_cycle.py` file in the function `test_sklearn_theorist`, and will be moved to a notebook file later.

The screenshot shows the setup code (left), initializing the `run` function along with the Theorist, random experimenter, and experimentalist (with a noise source to make it more realistic). On the right is the result of the run, with the data from each "experiment cycle" shown in a different color, and the theorist's fit in orange. 
> **Caveat:** I've tuned the parameters so that DARTS actually fits properly, it's still extremely unstable and most of the fits were completely off. I don't think that's a problem with the cycle though, more a problem with DARTS.

Screen Shot 2022-10-12 at 08 59 17

The important parts are:
- Initialize the cycle
```python
    experimentalist_results_run = run(
```
- Specify where the cycle begins – here with the "experimentalist" as we have neither data nor a list of samples to make
```python
        first_state=AERModule.EXPERIMENTALIST,
```
- Specify the theorist. Here we have a function which wraps the DARTSRegressor and gives it the right interface for our cycler. In place of the DARTSRegressor, we could use any scikit-learn compatible regressor.
```python
        theorist=scikit_learn_regressor_theorist_wrapper(
            DARTSRegressor(
                num_graph_nodes=2,
                param_updates_per_epoch=1,
                max_epochs=100,
                primitives=("none", "linear", "add", "subtract"),
            )
        ),
```
- Specify the experimentalist. We have a simple function which samples random points between the minimum and maximum of the independent variables.
```python
        experimentalist=make_random_experimentalist(n_observations_per_experiment=50),
```
- Specify the experiment runner. We give it a "ground truth function" (here "x_plus_one") and also include a function which adds Gaussian noise, though this could also be any other noise distribution we could imagine and code
```python
        experiment_runner=make_synthetic_experiment_runner(
            x_plus_one, noise_source=instantiated_noise_source
        ),
```
- Specify the bounds
```python
        metadata=VariableCollection(
        independent_variables=[Variable(name="x1", value_range=(-5, 5))],
        dependent_variables=[Variable(name="y", value_range=(-10, 10))],
    ),
```
- Initialize the rest of the run function. Much of this can be replaced by defaults later.
```python
        search_space=None,
        data=DataSetCollection([None]),
        theories=TheoryCollection([None]),
        independent_variable_values=None,
        max_cycle_count=10,
        cycle_count=0,
    )
```

Implements #120
Implements #121 

### Type of change:
- New feature (non-breaking change which adds functionality)

### Questions
- How do we like the interface?

### CODE REVIEW

**Comment by hollandjg** [comment]
Hi @musslick @benwandrew @chadcwilliams @gtdang @listar2000 @mirestrepo, here's a first version of the closed-loop cycler working with the DARTS theorist and a random-sampler-experimenter. We'd be interested in your feedback to the interface in the `run` function, in particular how we pass in the Theorists and Experimentalists.
This builds on @gtdang's work in #118

**Comment by musslick** [comment]
> 
> * Specify the theorist. Here we have a function which wraps the DARTSRegressor and gives it the right interface for our cycler. In place of the DARTSRegressor, we could use any scikit-learn compatible regressor.
> 
> ```python
>         theorist=scikit_learn_regressor_theorist_wrapper(
>             DARTSRegressor(
>                 num_graph_nodes=2,
>                 param_updates_per_epoch=1,
>                 max_epochs=100,
>                 primitives=("none", "linear", "add", "subtract"),
>             )
>         ),
> ```
> 

Ben and I were wondering here: Why do we need a scikit_learn_regressor_theorist_wrapper if the DARTSRegressor is already sklearn compatible?

**Comment by musslick** [comment]
> 
> ```python
>         experiment_runner=make_synthetic_experiment_runner(
>             x_plus_one, noise_source=instantiated_noise_source
>         ),
> ```
> 
> * Specify the bounds
> 
> ```python
>         metadata=VariableCollection(
>         independent_variables=[Variable(name="x1", value_range=(-5, 5))],
>         dependent_variables=[Variable(name="y", value_range=(-10, 10))],
>     ),
> ```
> 

I'm also curious: How does the runner know which variable is the independent variable and which is the dependent variable? I.e., how does it know which of the two variables is the input of x_plus_one?

**Comment by mirestrepo** [comment]
Will you ever need to ask questions about the current state, current cycle count, or whether the cycle is still running? The current `run` interface doesn't give you an access point to the current state, the `Model` nor the `Machine` inside. And I'm just wondering if that's not something that will be necessary.  If I'm following, even using their little graph utility plugin will need access to that...

**Comment by chadcwilliams** [comment]
> > ```python
> >         experiment_runner=make_synthetic_experiment_runner(
> >             x_plus_one, noise_source=instantiated_noise_source
> >         ),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Specify the bounds
> > 
> > ```python
> >         metadata=VariableCollection(
> >         independent_variables=[Variable(name="x1", value_range=(-5, 5))],
> >         dependent_variables=[Variable(name="y", value_range=(-10, 10))],
> >     ),
> > ```
> 
> I'm also curious: How does the runner know which variable is the independent variable and which is the dependent variable? I.e., how does it know which of the two variables is the input of x_plus_one?

As I was digging through the code, I found that the runner has a function down the line that specifically pulls the independent_variable's range to create x_prime (see code below). 

`    
    def make_random_experimentalist(n_observations_per_experiment=10):
        def dummy_experimentalist(data, metadata: VariableCollection, theory):
            low = metadata.independent_variables[0].min
            high = metadata.independent_variables[0].max
            x_prime = np.random.uniform(low, high, n_observations_per_experiment)
            return x_prime

        return dummy_experimentalist
`

I am curious whether the code above is specifically only pulling the first independent_variables (when multiple exist), or if that also handles multiple IVs?

All-in-all, this code looks great and the interface is quite intuitive. Well done!

**Comment by gtdang** [comment]
> ```python
> ```python
>         experiment_runner=make_synthetic_experiment_runner(
>             x_plus_one, noise_source=instantiated_noise_source
>         ),
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Specify the bounds
> 
> ```python
>         metadata=VariableCollection(
>         independent_variables=[Variable(name="x1", value_range=(-5, 5))],
>         dependent_variables=[Variable(name="y", value_range=(-10, 10))],
>     ),
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> I'm also curious: How does the runner know which variable is the independent variable and which is the dependent variable? I.e., how does it know which of the two variables is the input of x_plus_one?
> 
> As I was digging through the code, I found that the runner has a function down the line that specifically pulls the independent_variable's range to create x_prime (see code below).
>     def make_random_experimentalist(n_observations_per_experiment=10):
>         def dummy_experimentalist(data, metadata: VariableCollection, theory):
>             low = metadata.independent_variables[0].min
>             high = metadata.independent_variables[0].max
>             x_prime = np.random.uniform(low, high, n_observations_per_experiment)
>             return x_prime
> 
>         return dummy_experimentalist
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> I am curious whether the code above is specifically only pulling the first independent_variables (when multiple exist), or if that also handles multiple IVs?
> All-in-all, this code looks great and the interface is quite intuitive. Well done!
> ```

Your intuition is correct Chad. At the moment the closed loop example with the dummy experimentalist currently only handles 1 IV. We should update the dummy to iterate over multiple IVs.

**Comment by hollandjg** [comment]
This exploratory branch has reached the end of its useful life.

**Pull request closed without merging**
