### PR TITLE
docs: allow jupyter notebooks in documentation

### LINKED ISSUE #110: Convert docs example to a Jupyter notebook
1. Convert the docs example page to a Jupyter notebook. 
**https://autoresearch.github.io/autora/theorist/darts/example/**

2. Publish the notebook to the Github Pages docs using one of the methods and replace the original example page.
**https://jupyterbook.org/en/stable/publish/gh-pages.html**

### PR DESCRIPTION
**Pull request by hollandjg**
# Description

Integrate Jupyter notebooks into online documentation.

ToDo:
- [x] resolves #110 
- [x] Add link to open on Colab
- [x] Add link to notebook location on GitHub (this could be possible using the `edit_uri` from the material for mkdocs theme)
- [x] Replace branch name `docs/jupyter-in-documentation` with `main` in main.html

# Type of change

- **docs**: Documentation only changes

# Features

- Replaced all `.md` files which were actually notebooks with working `.ipynb` notebooks.
- Added link from documentation to open the corresponding notebook in Google Colaboratory.

# Screenshots (Optional)
Screenshot 2023-03-29 at 14 18 48
Screenshot 2023-03-29 at 14 19 13
Screenshot 2023-03-28 at 12 23 26

### CODE REVIEW

**Review by chadcwilliams — APPROVED** [review]
Looks great! 

Only thing I wonder is if you think it would be useful to add a link within each notebook to itself on GitHub? These pages are read-only, but some users will definitely want to use the notebooks and play around with them. Adding a direct link to it might save them some time searching the repo for it.

Definitely very minor suggestion, and no problem if you're not interested. I will approve as is.

**Comment by hollandjg** [comment]
Hi @benwandrew and @musslick – the to-dos are finished on this PR now, and the BSR example has been merged as a notebook.

**Review by musslick — APPROVED** [review]
Quickly reviewed this, and it looks great to me. I'm foreseeing some merge conflicts with other open PRs (e.g., the experimentalist documentation), so probably best to get this merged ASAP, so we can build the other documentation on top.

**Review by benwandrew — APPROVED** [review]
also looks good to me

**Pull request merged**
