### PR TITLE
docs: fixing a few typos

### LINKED ISSUE #169: fix/typos-in-online-documentation
found a few typos while using DARTS' online documentation as a template for BSR

### PR DESCRIPTION
**Pull request by benwandrew**
## Description

Found sound typos and omissions in online documentation while using it as a template for BSR

Fixes #169 

### Type of change:
- Documentation update

### Features: 
- textual typo fix

### CODE REVIEW

**Comment by musslick** [comment]
Might just want to check with @hollandjg to see why the second build test isn't working? It's odd, given that it's just a minor change in the documentation.

**Comment by benwandrew** [comment]
> Might just want to check with @hollandjg to see why the second build test isn't working? It's odd, given that it's just a minor change in the documentation.

looks like it's passed now without me doing anything else... strange...

**Comment by benwandrew** [comment]
> > Might just want to check with @hollandjg to see why the second build test isn't working? It's odd, given that it's just a minor change in the documentation.
> 
> looks like it's passed now without me doing anything else... strange...

but now they are not passing again... i have been seeing the following error regularly, and now i'm not sure if it's local to me or global:

```
An unexpected error has occurred: CalledProcessError: command: ('/home/runner/.cache/pypoetry/virtualenvs/autora-X42fqSpF-py3.9/bin/python', '-mvirtualenv', '/home/runner/.cache/pre-commit/repopsmig3z3/py_env-python3.8', '-p', 'python3.8')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
```

**Comment by hollandjg** [comment]
This should be fixed now – the PR has been updated to include changes from #175

**Review by hollandjg — APPROVED** [review]

**Pull request merged**
