### PR TITLE
BMS tutorial added to theorist tutorial

### PR DESCRIPTION
**Pull request by TheLemonPig**
# Description

Resolves issue #523 

# Type of change

*Delete as appropriate:*
- **docs**: Documentation only changes

### CODE REVIEW

**Review by benwandrew — COMMENTED** [review]
looks like there's an issue with finding the image that is supposed to be rendered (although i do see the png file in the `img` directory). the path is analogous to that for the corresponding image in Experimentalist.ipynb, which renders just fine, so i'm not quite sure what the solution is. 

Screen Shot 2023-07-17 at 16 08 44

apart from that, looks like the `mkdocs.yml` has already been updated, and i'm guessing the content of the notebook has already been thoroughly vetted given its inclusion in the workshop?

**Comment by younesStrittmatter** [comment]
I remember that we had a similar problem before. I think you had to "attach" the images in the notebook.

**Comment by benwandrew** [comment]
yeah, i'm not sure and was confused because it is already coded as an attachment (as depicted in your image)... perhaps dragging it makes some difference, but i'm stumped.

**Review by musslick — CHANGES_REQUESTED** [review]
I think we wan to replace this with some advanced tutorial. E.g., tutorial on equation discovery. And use the tutorial you prepared for the modeling workshop.

**Pull request closed without merging**
