### PR TITLE
docs: Add Notebook Tutorial for Equation Discovery

### LINKED ISSUE #523: Integrate BMS tutorial from modeling workshop into autora as new "Theorist Tutorial"

### PR DESCRIPTION
**Pull request by TheLemonPig**
Copy & Paste Tutorial Notebook from ```autora-theorist-bms``` branch to ```autora``` branch

# Description

closes #523 

# Type of change

*Delete as appropriate:*
- **docs**: Documentation only changes

### CODE REVIEW

**Comment by TheLemonPig** [comment]
Linking to AutoRA Project #523

**Review by younesStrittmatter — CHANGES_REQUESTED** [review]
The synthetic experiment runners interface has slightly changed (added_noise in the run function, not in the initialisation)

**Comment by benwandrew** [comment]
> added_noise

also need to update the function name from `experiment_runner` to `run`, which i think i handled successfully in latest commit.

**Review by benwandrew — APPROVED** [review]
i think this looks good now!

**Comment by benwandrew** [comment]
oh, i guess there's actually an error with the last cell under 6. Plot the Results for the Polynomial Regressor (no attribute `model_`, which is not included in the `__init__` for that class). can we just delete the cell trying to print `poly_model.model_`?

**Comment by TheLemonPig** [comment]
@younesStrittmatter I am not sure why but merging is blocked because of your request for changes but it isn't saying I can re-request your review. Is there anything you can do on your end?

**Comment by TheLemonPig** [comment]
@younesStrittmatter anything you see still needing to be changed for this PR?

**Review by younesStrittmatter — APPROVED** [review]

**Pull request merged**
