### PR TITLE
chore: move `autora/` to `src/autora/`

### PR DESCRIPTION
**Pull request by hollandjg**
## Description

This annoying change fixes a problem where PyCharm automatically creates incorrect import statements. This occurred in test cases 

### Type of change:
- Major bug fix

### Consequences: 
- All current PRs will need to be updated with the new paths

#### Setup
- Create a new file
- Assign the name `DARTSRegressor` to a variable without importing it first
- Put cursor on the red-underlined text
- Click Alt + Enter
Screen Shot 2022-12-14 at 15 39 09

#### Correct new behavior
- The correct path `autora.skl.darts.DARTSRegressor` is imported
  Screen Shot 2022-12-14 at 15 39 23
- The code works locally
- The code works in the GitHub actions test runner

#### Erroneous old behavior
- An incorrect path `skl.darts.DARTSRegressor` is imported
  Screen Shot 2022-12-14 at 15 41 19

- The code works locally (because of a quirk of how PyCharm functions)
- ⚠️ The code doesn't work on GitHub.

### CODE REVIEW

**Review by benwandrew — APPROVED** [review]
ooh, good catch!

**Review by gtdang — APPROVED** [review]
Great!

**Comment by hollandjg** [comment]
Let's not merge this until January.

**Review by musslick — APPROVED** [review]
Sounds good. Let's do the pull all together during the next in-person hackathon?

**Comment by hollandjg** [comment]
we're going to put off this change until February, during the next major clean-up of the code.

**Pull request closed without merging**
