### PR TITLE
fix: Fixed broken links and table of contents

### PR DESCRIPTION
**Pull request by chadcwilliams**
# Description

Fixed broken links and broken table of contents in the 4 basic tutorials

*If the issue is on Github, simply link to it using the '#' symbol; otherwise, provide a notion page link)*:
- No issue made (whoops)

# Type of change
- **fix**: A bug fix

### CODE REVIEW

**Review by musslick — APPROVED** [review]
Looks great!

**Review by hollandjg — CHANGES_REQUESTED** [review]
Hey Chad, thanks for putting these changes together! The changes you made make sense.

It looks like you've removed the output from the notebooks, and that means that they will render without the graphs on the web. I don't think that's intended. If you just rerun all the notebooks and save them with the output, then the graphs will reappear.

**Comment by chadcwilliams** [comment]
> Hey Chad, thanks for putting these changes together! The changes you made make sense.
> 
> It looks like you've removed the output from the notebooks, and that means that they will res nder without the graphs on the web. I don't think that's intended. If you just rerun all the notebooks and save them with the output, then the graphs will reappear.

This actually was on purpose because we have nb-clean as part of our commit pipeline, but now that you mention it that definitely doesn't make sense in this case. Just committed with the outputs back in!

**Review by hollandjg — APPROVED** [review]
Looks good to me!

**Pull request merged**
